apiVersion: v1
kind: Service
metadata:
  name: backend-invesstor
  namespace: default
  labels:
    app: backend-invesstor
spec:
  type: LoadBalancer
  selector:
    app: backend-invesstor
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
