apiVersion: v1
kind: Service
metadata:
  name: react-invesstor
  namespace: default
  labels:
    app: react-invesstor
spec:
  type: LoadBalancer
  selector:
    app: react-invesstor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
